baseurl = "http://www.skyportsystems.com/"
languageCode = "en-us"
title = "Skyport Systems"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true

[indexes]
  tag = "tags"